// example/vue-wrapper.vue
<!--
  vue-wrapper.vue

  A Vue 3 wrapper component for momentum-picker.
  Uses onMounted / onUnmounted to manage the picker lifecycle.

  Usage:
    <MomentumPickerVue
      :is-open="showPicker"
      mode="datetime"
      :value="selectedDate"
      @confirm="onConfirm"
      @cancel="onCancel"
      @change="onChange"
    />
-->

<template>
  <!-- Hidden mount point for the vanilla picker overlay -->
  <div ref="containerRef" aria-hidden="true" />
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from "vue";
import MomentumPicker from "../src/index"; // use 'momentum-picker' after npm install
import type { PickerOptions, PickerMode, PickerTheme } from "../src/types";

// ── Props ──────────────────────────────────────────────────────────────────

interface Props {
  isOpen?: boolean;
  mode?: PickerMode;
  value?: Date;
  minDate?: Date;
  maxDate?: Date;
  minuteStep?: number;
  format?: string;
  locale?: string;
  theme?: PickerTheme;
  primaryColor?: string;
  itemHeight?: number;
  visibleRows?: number;
}

const props = withDefaults(defineProps<Props>(), {
  isOpen: false,
  mode: "datetime",
  visibleRows: 5,
  itemHeight: 44,
  theme: "light",
  primaryColor: "#007aff",
  minuteStep: 1,
});

// ── Emits ──────────────────────────────────────────────────────────────────

const emit = defineEmits<{
  /** Fired every time a wheel column changes. */
  change: [date: Date, formatted?: string];
  /** Fired when user taps Done. */
  confirm: [date: Date, formatted?: string];
  /** Fired when user taps Cancel or presses Escape. */
  cancel: [];
}>();

// ── Internal refs ──────────────────────────────────────────────────────────

const containerRef = ref<HTMLDivElement | null>(null);
let picker: MomentumPicker | null = null;

// ── Lifecycle ──────────────────────────────────────────────────────────────

onMounted(() => {
  if (!containerRef.value) return;

  const options: PickerOptions = {
    container: containerRef.value,
    mode: props.mode,
    value: props.value ?? new Date(),
    minDate: props.minDate,
    maxDate: props.maxDate,
    minuteStep: props.minuteStep,
    format: props.format,
    locale: props.locale,
    theme: props.theme,
    primaryColor: props.primaryColor,
    itemHeight: props.itemHeight,
    visibleRows: props.visibleRows,
    onChange: (date, formatted) => emit("change", date, formatted),
    onConfirm: (date, formatted) => emit("confirm", date, formatted),
    onCancel: () => emit("cancel"),
  };

  picker = new MomentumPicker(options);

  // Respect initial isOpen state
  if (props.isOpen) picker.show();
});

onUnmounted(() => {
  picker?.destroy();
  picker = null;
});

// ── Watchers ───────────────────────────────────────────────────────────────

watch(
  () => props.isOpen,
  (isOpen) => {
    if (!picker) return;
    if (isOpen) {
      picker.show();
    } else {
      picker.hide();
    }
  },
);

watch(
  () => props.value,
  (newVal) => {
    if (picker && newVal) picker.setValue(newVal);
  },
);

watch(
  () => [props.theme, props.primaryColor] as const,
  ([theme, primaryColor]) => {
    picker?.setOptions({ theme, primaryColor });
  },
);
</script>

<!--
  Example parent usage:
  ─────────────────────────────────────────────────────────

  <template>
    <div>
      <p>Selected: {{ selectedDate.toLocaleString() }}</p>
      <button @click="showPicker = true">Open Picker</button>

      <MomentumPickerVue
        :is-open="showPicker"
        mode="datetime"
        :value="selectedDate"
        format="YYYY-MM-DD HH:mm"
        @confirm="onConfirm"
        @cancel="showPicker = false"
      />
    </div>
  </template>

  <script setup lang="ts">
  import { ref } from 'vue';
  import MomentumPickerVue from './vue-wrapper.vue';

  const showPicker = ref(false);
  const selectedDate = ref(new Date());

  const onConfirm = (date: Date, formatted?: string) => {
    selectedDate.value = date;
    showPicker.value = false;
    console.log('Confirmed:', formatted ?? date);
  };
  <\/script>
-->

// example/react-wrapper.tsx
/**
 * react-wrapper.tsx
 *
 * A React wrapper component for momentum-picker.
 * Uses a ref to mount/destroy the vanilla MomentumPicker class.
 *
 * Usage:
 *   import MomentumPickerReact from './react-wrapper';
 *
 *   <MomentumPickerReact
 *     mode="datetime"
 *     value={new Date()}
 *     isOpen={open}
 *     onConfirm={(date) => console.log(date)}
 *     onCancel={() => setOpen(false)}
 *   />
 */

import React, {
  useRef,
  useEffect,
  useCallback,
  type FC,
} from "react";
import MomentumPicker from "../src/index"; // adjust to 'momentum-picker' after npm install
import type { PickerOptions, PickerMode, PickerTheme } from "../src/types";

// ─────────────────────────────────────────────────────────────────────────────

interface MomentumPickerReactProps
  extends Omit<PickerOptions, "container" | "onChange" | "onConfirm" | "onCancel"> {
  /** Controls visibility (controlled component pattern). */
  isOpen?: boolean;
  /** Callback with the confirmed Date. */
  onConfirm?: (date: Date, formatted?: string) => void;
  /** Called when user taps Cancel or presses Escape. */
  onCancel?: () => void;
  /** Called whenever a wheel column changes. */
  onChange?: (date: Date, formatted?: string) => void;
}

// ─────────────────────────────────────────────────────────────────────────────

const MomentumPickerReact: FC<MomentumPickerReactProps> = ({
  isOpen = false,
  mode = "datetime",
  value,
  minDate,
  maxDate,
  minuteStep,
  format,
  locale,
  theme,
  primaryColor,
  itemHeight,
  visibleRows,
  onChange,
  onConfirm,
  onCancel,
}) => {
  // A hidden div that acts as the container for the vanilla picker
  const containerRef = useRef<HTMLDivElement>(null);
  // Store the picker instance across renders
  const pickerRef = useRef<MomentumPicker | null>(null);

  /**
   * Initialise the picker once after first mount.
   * The container div is appended to document.body so the overlay
   * can cover the full viewport correctly.
   */
  useEffect(() => {
    if (!containerRef.current) return;

    const options: PickerOptions = {
      container: containerRef.current,
      mode: mode as PickerMode,
      value: value ?? new Date(),
      minDate,
      maxDate,
      minuteStep,
      format,
      locale,
      theme: theme as PickerTheme,
      primaryColor,
      itemHeight,
      visibleRows,
      onChange,
      onConfirm,
      onCancel,
    };

    pickerRef.current = new MomentumPicker(options);

    return () => {
      // Clean up on unmount
      pickerRef.current?.destroy();
      pickerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // intentionally empty — initialise once

  // ── Sync isOpen prop → show/hide ──────────────────────────────────────────
  useEffect(() => {
    if (!pickerRef.current) return;
    if (isOpen) {
      pickerRef.current.show();
    } else {
      pickerRef.current.hide();
    }
  }, [isOpen]);

  // ── Sync value prop → setValue ────────────────────────────────────────────
  useEffect(() => {
    if (!pickerRef.current || !value) return;
    pickerRef.current.setValue(value);
  }, [value]);

  // ── Sync theme / primaryColor changes ─────────────────────────────────────
  useEffect(() => {
    pickerRef.current?.setOptions({ theme: theme as PickerTheme, primaryColor });
  }, [theme, primaryColor]);

  // Container is invisible — picker renders its own overlay inside it
  return <div ref={containerRef} aria-hidden="true" />;
};

export default MomentumPickerReact;

// ─────────────────────────────────────────────────────────────────────────────
// Example usage (not part of the wrapper, for illustration only):
// ─────────────────────────────────────────────────────────────────────────────

const ExampleApp: FC = () => {
  const [open, setOpen] = React.useState(false);
  const [selectedDate, setSelectedDate] = React.useState<Date>(new Date());

  const handleConfirm = useCallback((date: Date) => {
    setSelectedDate(date);
    setOpen(false);
  }, []);

  const handleCancel = useCallback(() => {
    setOpen(false);
  }, []);

  return (
    <div style={{ padding: 24, fontFamily: "sans-serif" }}>
      <h1>momentum-picker React Demo</h1>
      <p>Selected: {selectedDate.toLocaleString()}</p>
      <button
        onClick={() => setOpen(true)}
        style={{
          background: "#007aff",
          color: "#fff",
          border: "none",
          padding: "12px 24px",
          borderRadius: 12,
          fontSize: 16,
          cursor: "pointer",
          marginTop: 16,
        }}
      >
        Open Picker
      </button>

      <MomentumPickerReact
        isOpen={open}
        mode="datetime"
        value={selectedDate}
        format="YYYY-MM-DD HH:mm"
        onConfirm={handleConfirm}
        onCancel={handleCancel}
        onChange={(date) => console.log("onChange", date)}
      />
    </div>
  );
};

export { ExampleApp };
